server.port: 8080
eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://postgres-db1:5432/db1
    username: user1
    password: password1
  jpa:
    hibernate:
      ddl-auto: create

user:
  role.service.url: http://user-role-service:8082
  fullname.service.url: http://user-fullname-service:8081