server.port: 8082
eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://postgres-db3:5432/db3
    username: user3
    password: password3
  jpa:
    hibernate:
      ddl-auto: create

user.service.url: http://user-service:8080